### PR TITLE
Introduce jetpack.io devbox for better dev env reproducibility & replace npm with pnpm

### PR DESCRIPTION
**Pull request by yeongsheng-tan**
1. Adding devbox.sh tooling to allow better dev environment setup and reproducibility
2. replace npm with pnpm (clean up scripts) - define workspace packages of 'project' & 'integration-tests'
3. replace pm2 with npm-run-all2 for integration-test
4. general version bumps for node_modules across workspace packages of 'project' & 'integration-tests'

### CODE REVIEW

**Comment by yeongsheng-tan** [comment]
@AngelaE hope you could take a look at this attempt to rejuvenate tooling for building & testing ts-mountebank.
I am a benefactor of this wonderful test abstraction tool for mountebank (another great piece of test tool) and would like to help to contribute to some slight improvements to the overall tool-chain and aesthetics.

Thank you for your time and this great tool.

**Comment by AngelaE** [comment]
> @AngelaE hope you could take a look at this attempt to rejuvenate tooling for building & testing ts-mountebank. I am a benefactor of this wonderful test abstraction tool for mountebank (another great piece of test tool) and would like to help to contribute to some slight improvements to the overall tool-chain and aesthetics.
> 
> Thank you for your time and this great tool.

Hi @yeongsheng-tan - thanks for your contribution! I have been very busy and am just starting to look through this. It may take me a bit because I need to read up on pnpm, nix and devbox. May I ask why you  made these two change (npm => pnpm and adding devbox) in a single PR rather than two separate ones?

**Comment by yeongsheng-tan** [comment]
> > @AngelaE hope you could take a look at this attempt to rejuvenate tooling for building & testing ts-mountebank. I am a benefactor of this wonderful test abstraction tool for mountebank (another great piece of test tool) and would like to help to contribute to some slight improvements to the overall tool-chain and aesthetics.
> > Thank you for your time and this great tool.
> 
> Hi @yeongsheng-tan - thanks for your contribution! I have been very busy and am just starting to look through this. It may take me a bit because I need to read up on pnpm, nix and devbox. May I ask why you made these two change (npm => pnpm and adding devbox) in a single PR rather than two separate ones?

You are right. I should break it into 2 PRs.

**Comment by yeongsheng-tan** [comment]
@AngelaE please see the new 1st PR for introducing devbox.sh https://github.com/AngelaE/ts-mountebank/pull/26

**Comment by yeongsheng-tan** [comment]
@AngelaE please find the 2nd PR for replacing/migration `npm` to `pnpm` https://github.com/AngelaE/ts-mountebank/pull/27. Again, much appreciate you taking your valuable and precious time and effort to consider my contribution.

**Comment by AngelaE** [comment]
This is replaced by #26 and #27

**Pull request closed without merging**
